# Generated by Django 5.1.5 on 2025-01-30 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='FuelConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_trips', models.PositiveIntegerField()),
                ('purpose', models.CharField(help_text='Trip purpose/description', max_length=200)),
                ('total_liters', models.FloatField(editable=False)),
                ('cost', models.FloatField(editable=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel.driver')),
            ],
            options={
                'verbose_name': 'Fuel Consumption',
                'verbose_name_plural': 'Fuel Consumptions',
                'unique_together': {('driver', 'date')},
            },
        ),
    ]
