# Generated by Django 4.2.17 on 2025-06-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsumption',
            name='destination',
            field=models.CharField(choices=[('dipolog', 'Dipolog - 2500km'), ('cagayan', 'Cagayan - 5000km'), ('margosatubig', 'Margosatubig - 2000km'), ('pagadian_city', 'Pagadian City - 1000km'), ('ozamiz_city', 'Ozamiz City - 1500km'), ('zamboanga_city', 'Zamboanga City - 5000km'), ('ipil', 'Ipil - 3500km'), ('sindangan', 'Sindangan - 1500km'), ('local', 'Local Area')], default='local', max_length=100),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='purpose',
            field=models.CharField(choices=[('Transport Patient', 'Transport Patient'), ('reroute river manlabay', 'Reroute River Manlabay'), ('landslide dapiwak', 'Landslide Dapiwak'), ('landslide san vicente', 'Landslide San Vicente'), ('landslide senote', 'Landslide Senote')], default='Transport Patient', max_length=255),
        ),
    ]
