# Generated by Django 4.2.17 on 2025-06-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_fuelconsumption_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsumption',
            name='reference_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='destination',
            field=models.CharField(choices=[('dipolog', 'Dipolog'), ('cagayan', 'Cagayan'), ('margosatubig', 'Margosatubig'), ('pagadian_city', 'Pagadian City'), ('ozamiz_city', 'Ozamiz City'), ('zamboanga_city', 'Zamboanga City'), ('ipil', 'Ipil'), ('sindangan', 'Sindangan'), ('local', 'Local Area')], default='local', max_length=100),
        ),
    ]
