# Generated by Django 5.2.3 on 2025-07-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_fuelconsumption_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelconsumption',
            name='destination',
            field=models.CharField(choices=[('dipolog', 'Dipolog'), ('cagayan', 'Cagayan'), ('margosatubig', 'Margosatubig'), ('pagadian_city', 'Pagadian City'), ('ozamiz_city', 'Ozamiz City'), ('zamboanga_city', 'Zamboanga City'), ('ipil', 'Ipil'), ('sindangan', 'Sindangan'), ('local', 'Local Area'), ('mahayag', 'Mahayag (Special Budget Utilization)')], default='local', max_length=100),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='purpose',
            field=models.CharField(choices=[('Transport Patient', 'Transport Patient'), ('landslide sinonok', 'Landslide Sinonok'), ('landslide bag-ong kauswagan', 'Landslide Bag-ong Kauswagan'), ('landslide macasing', 'Landslide Macasing'), ('mahayag medicare', 'Mahayag Medicare')], default='Transport Patient', max_length=255),
        ),
    ]
