# Generated by Django 5.2.3 on 2025-09-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0005_alter_fuelconsumption_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelconsumption',
            name='destination',
            field=models.CharField(choices=[('dipolog', 'Dipolog'), ('cagayan', 'Cagayan'), ('margosatubig', 'Margosatubig'), ('pagadian_city', 'Pagadian City'), ('ozamiz_city', 'Ozamiz City'), ('zamboanga_city', 'Zamboanga City'), ('ipil', 'Ipil'), ('sindangan', 'Sindangan'), ('molave_blancia_hospital', 'Molave Blancia Hospital'), ('local', 'Local Area'), ('mahayag', 'Mahayag Medicare')], default='local', max_length=100),
        ),
    ]