# Generated by Django 4.2.23 on 2025-09-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0006_add_molave_blancia_hospital_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsumption',
            name='actual_fuel_price',
            field=models.FloatField(default=62.0),
        ),
    ]