# Generated by Django 4.2.23 on 2025-10-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0007_fuelconsumption_actual_fuel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsumption',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsumption',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsumption',
            name='return_arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsumption',
            name='return_departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
