# Generated by Django 4.2.23 on 2025-10-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0008_fuelconsumption_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsumption',
            name='consumed_liters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsumption',
            name='finished_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsumption',
            name='starting_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
