# Generated by Django 5.2.4 on 2025-10-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0009_fuelconsumption_consumed_liters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsumption',
            name='passenger_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
