# Generated by Django 5.2.17 on 2026-08-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0010_fuelconsumption_passenger_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsumption',
            name='or_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='destination',
            field=models.CharField(choices=[('dipolog', 'Dipolog'), ('cagayan', 'Cagayan'), ('margosatubig', 'Margosatubig'), ('pagadian_city', 'Pagadian City'), ('ozamiz_city', 'Ozamiz City'), ('zamboanga_city', 'Zamboanga City'), ('davao_city', 'Davao City'), ('ipil', 'Ipil'), ('sindangan', 'Sindangan'), ('molave_blancia_hospital', 'Molave Blancia Hospital'), ('local', 'Local Area'), ('mahayag', 'Mahayag Medicare')], default='local', max_length=100),
        ),
    ]
