# Generated by Django 5.2.17 on 2026-08-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0011_fuelconsumption_or_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('check_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
