# Generated by Django 5.2.17 on 2026-08-18 05:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0012_liquidationsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True)),
                ('report_date', models.DateField(default=datetime.date.today)),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('check_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidationReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('or_number', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_type', models.CharField(default='Diesel', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fuel.liquidationreport')),
            ],
        ),
    ]
