# Generated by Django 5.2.17 on 2026-08-24 08:05

import datetime
import django.db.models.deletion
import fuel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0013_liquidationreport_liquidationreportentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(blank=True, help_text='PCV No.', max_length=50)),
                ('voucher_date', models.DateField(default=datetime.date.today)),
                ('fund', models.CharField(blank=True, default='', max_length=100)),
                ('fpp', models.CharField(blank=True, max_length=100, verbose_name='FPP')),
                ('payee_office', models.CharField(default='MDRRMO', max_length=150)),
                ('address', models.CharField(default='Dumingag, Zamboanga del Sur', max_length=255)),
                ('particulars', models.TextField(blank=True, help_text='Particulars (one per line or free text)')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purpose', models.TextField(blank=True)),
                ('requested_by_name', models.CharField(blank=True, max_length=150)),
                ('approved_by_name', models.CharField(default='JHUNAX L. CARDOZA', max_length=150)),
                ('paid_by_name', models.CharField(default='JHUNAX L. CARDOZA', max_length=150)),
                ('cash_received_by_name', models.CharField(blank=True, max_length=150)),
                ('total_amount_granted', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount_paid_per_or', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('or_invoice_no', models.CharField(blank=True, max_length=100)),
                ('amount_refunded', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('received_refund', models.BooleanField(default=False)),
                ('reimbursement_paid', models.BooleanField(default=False)),
                ('liquidation_submitted', models.BooleanField(default=False)),
                ('reimbursement_received_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Petty Cash Voucher',
                'verbose_name_plural': 'Petty Cash Vouchers',
                'ordering': ['-voucher_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReimbursementExpenseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(blank=True, default='', max_length=150)),
                ('fund_cluster', models.CharField(blank=True, max_length=100)),
                ('receipt_date', models.DateField(default=datetime.date.today)),
                ('rer_no', models.CharField(blank=True, max_length=50, verbose_name='RER No.')),
                ('received_from_name', models.CharField(blank=True, max_length=150, verbose_name='Received from (Name)')),
                ('received_from_designation', models.CharField(blank=True, max_length=150, verbose_name='Official Designation')),
                ('amount_in_words', models.CharField(blank=True, max_length=255, verbose_name='Amount in Words')),
                ('amount_in_figures', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount in Figures (P)')),
                ('in_payment_for', models.TextField(blank=True, help_text='e.g., Payments for subsistence, services, rental or transportation should show inclusive dates, purpose, distance, points of travel, etc.', verbose_name='In payment for')),
                ('payee_signature_name', models.CharField(blank=True, max_length=150, verbose_name='Payee Name')),
                ('payee_address', models.CharField(blank=True, max_length=255)),
                ('payee_residence_cert_no', models.CharField(blank=True, max_length=100)),
                ('payee_residence_date', models.DateField(blank=True, null=True)),
                ('payee_residence_place', models.CharField(blank=True, max_length=150)),
                ('witness_signature_name', models.CharField(blank=True, max_length=150, verbose_name='Witness Name')),
                ('witness_address', models.CharField(blank=True, max_length=255)),
                ('witness_residence_cert_no', models.CharField(blank=True, max_length=100)),
                ('witness_residence_date', models.DateField(blank=True, null=True)),
                ('witness_residence_place', models.CharField(blank=True, max_length=150)),
                ('attached_image', models.ImageField(blank=True, null=True, upload_to=fuel.models.rer_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('petty_cash_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rers', to='fuel.pettycashvoucher')),
            ],
            options={
                'verbose_name': 'Reimbursement Expense Receipt',
                'verbose_name_plural': 'Reimbursement Expense Receipts',
                'ordering': ['-receipt_date', '-id'],
            },
        ),
    ]
