# Generated by Django 5.2.17 on 2026-08-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0016_add_rer_multiple_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidationreport',
            name='amount_refund_per_or',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount Refund per OR #', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='liquidationreport',
            name='amount_reimbursed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount Reimbursed', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='liquidationreportentry',
            name='wht1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Withholding Tax 1% (editable per row)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='liquidationreportentry',
            name='wht5_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Withholding Tax 5% (editable per row, overrides computed)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='liquidationsetting',
            name='amount_refund_per_or',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount Refund per OR # (footer)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='liquidationsetting',
            name='amount_reimbursed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount Reimbursed (footer)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='liquidationreportentry',
            name='vat_inclusive',
            field=models.BooleanField(default=True, help_text='VAT inclusive - checked: amount includes 12% VAT (WHT = amount/1.12*rate). Unchecked: Non-VAT (no withholding, Net = Amount)'),
        ),
    ]
