# Generated by Django 5.2.17 on 2026-08-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0017_add_liquidation_dynamic_footer_wht'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidationreport',
            name='refund_or_number',
            field=models.CharField(blank=True, help_text='OR Number for Amount Refund per OR #', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liquidationsetting',
            name='refund_or_number',
            field=models.CharField(blank=True, help_text='OR Number for Amount Refund per OR #', max_length=50, null=True),
        ),
    ]
